# config/server.yml
server:
  listen_port: 8080  # The port your proxy will listen on

database:
  type: postgresql  # Specify your database type: postgresql, mysql, sqlserver
  host: localhost   # Database host
  port: 5432        # Default PostgreSQL port (change for other DBMSs)
  db_name: testdb
  user: huyong97
  password: password
  max_connections: 100  # Maximum connections to allow

detection:
  window_size: 60  # Time window in seconds for rate monitoring
  threshold:
    queries_per_minute: 30  # Max queries per minute per client
    failed_queries_per_minute: 10  # Max failed queries per minute
    avg_query_time: 5.0  # Alert if average query time exceeds this value
